
services:
  db:
    image: postgres:13
    container_name: ctn-sds-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  django:
    build:
      context: .
    container_name: ctn-sds-django
    image: img-sds-django
    volumes:
      - static_volume:/app/static
      - media_volume:/app/uploads
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: ctn-sds-nginx
    image: img-sds-nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/uploads
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data: